import { namesOne, namesTwo } from "./names.js";

const initApp = () => {
  document.getElementById("main__form").addEventListener("submit", (event) => {
    event.preventDefault() /*submit reloads the entire web page by default, .preventDefault() method used to override*/
    clearAll();
    const nameArray = generateNames();
    displayNames(nameArray);
  })
} /*initApp() function kicks off all the subsequent functions needed to generate a random name*/

document.addEventListener("DOMContentLoaded", initApp);

const clearAll = () => {
  document.querySelector(".main__section ol").innerHTML = "";
} /*Resets the display area so that there isn't a large accumulation of data in case use the app multiple times.*/

const generateNames = () => {
  const numberArray = [];
  for(let i=0; i<3;){
  const numb = Math.floor(Math.random()*10);
  if (numberArray.includes(numb)){
    continue
  } else {
    numberArray.push(numb);
    i++;}}
  
  const nameOne = namesOne[numberArray[0]] + namesTwo[numberArray[1]];
  const nameTwo = namesOne[numberArray[1]] + namesTwo[numberArray[2]];
  const nameThree = namesOne[numberArray[2]] + namesTwo[numberArray[0]];

  return [nameOne, nameTwo, nameThree];
} /*Random name is generated by creating a random number to put in Array, ensuring that the number doesn't repeat in the array and then using those numbers to select a name from the names.js document*/

const displayNames = (nameList) => {
  const list = document.querySelector(".main__section ol");
  const input = document.getElementById("form__input").value;
  nameList.forEach(name => {
    list.innerHTML += `<li class ="list__header"><h2><a href="https://www.youtube.com/@${name}">${name}</a></h2></li>`;
    list.innerHTML += `<ul class="unordered__list"><br><li class="unorderd__item"><a href="https://www.youtube.com/@${input}s${name}">${input}s${name}</a></li>
    <br><li class="unorderd__item"><a href="https://www.youtube.com/@${name}With${input}">${name}With${input}</a></li></ul>
    <br>`
  });
} /*Used a forEach loop to enter HTML text and display suggested names*/