import { namesOne, namesTwo } from "./names.js";

const initApp = () => {
  document.getElementById("main__form").addEventListener("submit", (event) => {
    event.preventDefault() /*submit reloads the entire web page by default, .preventDefault() method used to override*/
    clearAll();
    const nameArray = generateNames();
  })
} /*initApp() function kicks off all the subsequent functions needed to generate a random name*/

document.addEventListener("DOMContentLoaded", initApp);

/* ||GLOBAL SELECTORS */
const display = document.getElementById("main__section")

const clearAll = () => {
  display.innerHTML = "";
} /*Resets the display area so that there isn't a large accumulation of data in case use the app multiple times.*/

const generateNames = () => {
  const numberArray = [];
  for(let i=0; i<3;){
  const numb = Math.floor(Math.random()*10);
  if (numberArray.includes(numb)){
    continue
  } else {
    numberArray.push(numb);
    i++;}}
  
  const nameOne = namesOne[numberArray[0]] + namesTwo[numberArray[1]];
  const nameTwo = namesOne[numberArray[1]] + namesTwo[numberArray[2]];
  const nameThree = namesOne[numberArray[2]] + namesTwo[numberArray[0]];

  return [nameOne, nameTwo, nameThree];
} /*Random name is generated by creating a random number to put in Array, ensuring that the number doesn't repeat in the array and then using those numbers to select a name from the names.js document*/
